### ISSUE TITLE
Set-up Persistant Storage on OCP

### ISSUE THREAD

**Issue by arthomasredhat** [redhat-manufacturing/osdu-lab-gitops#5]

**Comment by arthomasredhat** [comment]
Set-up Repo with ODF

**Comment by arthomasredhat** [comment]
@jarcher Can you add success criteria for this task?

**Comment by arthomasredhat** [comment]
Per Rakesh, we need to check per unit server the number of  SSD's available.

**Comment by codekow** [comment]
@arthomasredhat Persistent stoarge is setup on the cluster

See the following:
- https://github.com/redhat-manufacturing/osdu-lab-gitops/blob/main/components/argocd/apps/overlays/hou-edge/app-odf-instance.yaml
- https://github.com/redhat-manufacturing/osdu-lab-gitops/blob/5ebe86b2d2baf42a54c7dfbe7096bcd50d699ce2/components/argocd/apps/overlays/hou-edge/patch-operators-applicationset.yaml#L22
